// import ForceGraph3D from '3d-force-graph';
import ForceGraph3D from 'react-force-graph-3d';
import React, { useState, useEffect } from "react";
import { basics } from "../services/basics";
import mis from './miserable.json'


// the graph configuration, you only need to pass down properties
// that you want to override, otherwise default ones will be used


export const Canvas = () => {
    const NODES = 300;
    const GROUPS = 12;
    const gData = {
      "nodes": [
        {"id": "Myriel", "group": 1},
        {"id": "Napoleon", "group": 1},
        {"id": "Mlle.Baptistine", "group": 1},
        {"id": "Mme.Magloire", "group": 1},
        {"id": "CountessdeLo", "group": 1},
        {"id": "Geborand", "group": 1},
        {"id": "Champtercier", "group": 1},
        {"id": "Cravatte", "group": 1},
        {"id": "Count", "group": 1},
        {"id": "OldMan", "group": 1},
        {"id": "Labarre", "group": 2},
        {"id": "Valjean", "group": 2},
        {"id": "Marguerite", "group": 3},
        {"id": "Mme.deR", "group": 2},
        {"id": "Isabeau", "group": 2},
        {"id": "Gervais", "group": 2},
        {"id": "Tholomyes", "group": 3},
        {"id": "Listolier", "group": 3},
        {"id": "Fameuil", "group": 3},
        {"id": "Blacheville", "group": 3},
        {"id": "Favourite", "group": 3},
        {"id": "Dahlia", "group": 3},
        {"id": "Zephine", "group": 3},
        {"id": "Fantine", "group": 3},
        {"id": "Mme.Thenardier", "group": 4},
        {"id": "Thenardier", "group": 4},
        {"id": "Cosette", "group": 5},
        {"id": "Javert", "group": 4},
        {"id": "Fauchelevent", "group": 0},
        {"id": "Bamatabois", "group": 2},
        {"id": "Perpetue", "group": 3},
        {"id": "Simplice", "group": 2},
        {"id": "Scaufflaire", "group": 2},
        {"id": "Woman1", "group": 2},
        {"id": "Judge", "group": 2},
        {"id": "Champmathieu", "group": 2},
        {"id": "Brevet", "group": 2},
        {"id": "Chenildieu", "group": 2},
        {"id": "Cochepaille", "group": 2},
        {"id": "Pontmercy", "group": 4},
        {"id": "Boulatruelle", "group": 6},
        {"id": "Eponine", "group": 4},
        {"id": "Anzelma", "group": 4},
        {"id": "Woman2", "group": 5},
        {"id": "MotherInnocent", "group": 0},
        {"id": "Gribier", "group": 0},
        {"id": "Jondrette", "group": 7},
        {"id": "Mme.Burgon", "group": 7},
        {"id": "Gavroche", "group": 8},
        {"id": "Gillenormand", "group": 5},
        {"id": "Magnon", "group": 5},
        {"id": "Mlle.Gillenormand", "group": 5},
        {"id": "Mme.Pontmercy", "group": 5},
        {"id": "Mlle.Vaubois", "group": 5},
        {"id": "Lt.Gillenormand", "group": 5},
        {"id": "Marius", "group": 8},
        {"id": "BaronessT", "group": 5},
        {"id": "Mabeuf", "group": 8},
        {"id": "Enjolras", "group": 8},
        {"id": "Combeferre", "group": 8},
        {"id": "Prouvaire", "group": 8},
        {"id": "Feuilly", "group": 8},
        {"id": "Courfeyrac", "group": 8},
        {"id": "Bahorel", "group": 8},
        {"id": "Bossuet", "group": 8},
        {"id": "Joly", "group": 8},
        {"id": "Grantaire", "group": 8},
        {"id": "MotherPlutarch", "group": 9},
        {"id": "Gueulemer", "group": 4},
        {"id": "Babet", "group": 4},
        {"id": "Claquesous", "group": 4},
        {"id": "Montparnasse", "group": 4},
        {"id": "Toussaint", "group": 5},
        {"id": "Child1", "group": 10},
        {"id": "Child2", "group": 10},
        {"id": "Brujon", "group": 4},
        {"id": "Mme.Hucheloup", "group": "hcp"}
      ],
      "links": [
        {"source": "Napoleon", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Myriel", "value": 1},
        {"source": "Mlle.Baptistine", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Myriel", "value": 8},
        {"source": "Mme.Magloire", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Myriel", "value": 10},
        {"source": "Mme.Magloire", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mlle.Baptistine", "value": 6},
        {"source": "CountessdeLo", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Myriel", "value": 1},
        {"source": "Geborand", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Myriel", "value": 1},
        {"source": "Champtercier", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Myriel", "value": 1},
        {"source": "Cravatte", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Myriel", "value": 1},
        {"source": "Count", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Myriel", "value": 2},
        {"source": "OldMan", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Myriel", "value": 1},
        {"source": "Valjean", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Labarre", "value": 1},
        {"source": "Valjean", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mme.Magloire", "value": 3},
        {"source": "Valjean", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mlle.Baptistine", "value": 3},
        {"source": "Valjean", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Myriel", "value": 5},
        {"source": "Marguerite", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 1},
        {"source": "Mme.deR", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 1},
        {"source": "Isabeau", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 1},
        {"source": "Gervais", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 1},
        {"source": "Listolier", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Tholomyes", "value": 4},
        {"source": "Fameuil", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Tholomyes", "value": 4},
        {"source": "Fameuil", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Listolier", "value": 4},
        {"source": "Blacheville", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Tholomyes", "value": 4},
        {"source": "Blacheville", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Listolier", "value": 4},
        {"source": "Blacheville", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Fameuil", "value": 4},
        {"source": "Favourite", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Tholomyes", "value": 3},
        {"source": "Favourite", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Listolier", "value": 3},
        {"source": "Favourite", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Fameuil", "value": 3},
        {"source": "Favourite", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Blacheville", "value": 4},
        {"source": "Dahlia", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Tholomyes", "value": 3},
        {"source": "Dahlia", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Listolier", "value": 3},
        {"source": "Dahlia", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Fameuil", "value": 3},
        {"source": "Dahlia", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Blacheville", "value": 3},
        {"source": "Dahlia", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Favourite", "value": 5},
        {"source": "Zephine", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Tholomyes", "value": 3},
        {"source": "Zephine", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Listolier", "value": 3},
        {"source": "Zephine", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Fameuil", "value": 3},
        {"source": "Zephine", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Blacheville", "value": 3},
        {"source": "Zephine", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Favourite", "value": 4},
        {"source": "Zephine", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Dahlia", "value": 4},
        {"source": "Fantine", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Tholomyes", "value": 3},
        {"source": "Fantine", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Listolier", "value": 3},
        {"source": "Fantine", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Fameuil", "value": 3},
        {"source": "Fantine", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Blacheville", "value": 3},
        {"source": "Fantine", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Favourite", "value": 4},
        {"source": "Fantine", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Dahlia", "value": 4},
        {"source": "Fantine", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Zephine", "value": 4},
        {"source": "Fantine", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Marguerite", "value": 2},
        {"source": "Fantine", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 9},
        {"source": "Mme.Thenardier", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Fantine", "value": 2},
        {"source": "Mme.Thenardier", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 7},
        {"source": "Thenardier", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mme.Thenardier", "value": 13},
        {"source": "Thenardier", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Fantine", "value": 1},
        {"source": "Thenardier", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 12},
        {"source": "Cosette", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mme.Thenardier", "value": 4},
        {"source": "Cosette", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 31},
        {"source": "Cosette", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Tholomyes", "value": 1},
        {"source": "Cosette", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Thenardier", "value": 1},
        {"source": "Javert", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 17},
        {"source": "Javert", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Fantine", "value": 5},
        {"source": "Javert", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Thenardier", "value": 5},
        {"source": "Javert", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mme.Thenardier", "value": 1},
        {"source": "Javert", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Cosette", "value": 1},
        {"source": "Fauchelevent", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 8},
        {"source": "Fauchelevent", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Javert", "value": 1},
        {"source": "Bamatabois", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Fantine", "value": 1},
        {"source": "Bamatabois", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Javert", "value": 1},
        {"source": "Bamatabois", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 2},
        {"source": "Perpetue", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Fantine", "value": 1},
        {"source": "Simplice", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Perpetue", "value": 2},
        {"source": "Simplice", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 3},
        {"source": "Simplice", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Fantine", "value": 2},
        {"source": "Simplice", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Javert", "value": 1},
        {"source": "Scaufflaire", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 1},
        {"source": "Woman1", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 2},
        {"source": "Woman1", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Javert", "value": 1},
        {"source": "Judge", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 3},
        {"source": "Judge", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Bamatabois", "value": 2},
        {"source": "Champmathieu", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 3},
        {"source": "Champmathieu", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Judge", "value": 3},
        {"source": "Champmathieu", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Bamatabois", "value": 2},
        {"source": "Brevet", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Judge", "value": 2},
        {"source": "Brevet", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Champmathieu", "value": 2},
        {"source": "Brevet", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 2},
        {"source": "Brevet", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Bamatabois", "value": 1},
        {"source": "Chenildieu", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Judge", "value": 2},
        {"source": "Chenildieu", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Champmathieu", "value": 2},
        {"source": "Chenildieu", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Brevet", "value": 2},
        {"source": "Chenildieu", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 2},
        {"source": "Chenildieu", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Bamatabois", "value": 1},
        {"source": "Cochepaille", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Judge", "value": 2},
        {"source": "Cochepaille", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Champmathieu", "value": 2},
        {"source": "Cochepaille", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Brevet", "value": 2},
        {"source": "Cochepaille", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Chenildieu", "value": 2},
        {"source": "Cochepaille", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 2},
        {"source": "Cochepaille", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Bamatabois", "value": 1},
        {"source": "Pontmercy", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Thenardier", "value": 1},
        {"source": "Boulatruelle", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Thenardier", "value": 1},
        {"source": "Eponine", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mme.Thenardier", "value": 2},
        {"source": "Eponine", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Thenardier", "value": 3},
        {"source": "Anzelma", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Eponine", "value": 2},
        {"source": "Anzelma", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Thenardier", "value": 2},
        {"source": "Anzelma", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mme.Thenardier", "value": 1},
        {"source": "Woman2", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 3},
        {"source": "Woman2", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Cosette", "value": 1},
        {"source": "Woman2", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Javert", "value": 1},
        {"source": "MotherInnocent", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Fauchelevent", "value": 3},
        {"source": "MotherInnocent", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 1},
        {"source": "Gribier", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Fauchelevent", "value": 2},
        {"source": "Mme.Burgon", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Jondrette", "value": 1},
        {"source": "Gavroche", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mme.Burgon", "value": 2},
        {"source": "Gavroche", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Thenardier", "value": 1},
        {"source": "Gavroche", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Javert", "value": 1},
        {"source": "Gavroche", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 1},
        {"source": "Gillenormand", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Cosette", "value": 3},
        {"source": "Gillenormand", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 2},
        {"source": "Magnon", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gillenormand", "value": 1},
        {"source": "Magnon", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mme.Thenardier", "value": 1},
        {"source": "Mlle.Gillenormand", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gillenormand", "value": 9},
        {"source": "Mlle.Gillenormand", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Cosette", "value": 2},
        {"source": "Mlle.Gillenormand", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 2},
        {"source": "Mme.Pontmercy", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mlle.Gillenormand", "value": 1},
        {"source": "Mme.Pontmercy", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Pontmercy", "value": 1},
        {"source": "Mlle.Vaubois", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mlle.Gillenormand", "value": 1},
        {"source": "Lt.Gillenormand", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mlle.Gillenormand", "value": 2},
        {"source": "Lt.Gillenormand", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gillenormand", "value": 1},
        {"source": "Lt.Gillenormand", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Cosette", "value": 1},
        {"source": "Marius", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mlle.Gillenormand", "value": 6},
        {"source": "Marius", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gillenormand", "value": 12},
        {"source": "Marius", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Pontmercy", "value": 1},
        {"source": "Marius", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Lt.Gillenormand", "value": 1},
        {"source": "Marius", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Cosette", "value": 21},
        {"source": "Marius", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 19},
        {"source": "Marius", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Tholomyes", "value": 1},
        {"source": "Marius", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Thenardier", "value": 2},
        {"source": "Marius", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Eponine", "value": 5},
        {"source": "Marius", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gavroche", "value": 4},
        {"source": "BaronessT", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gillenormand", "value": 1},
        {"source": "BaronessT", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Marius", "value": 1},
        {"source": "Mabeuf", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Marius", "value": 1},
        {"source": "Mabeuf", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Eponine", "value": 1},
        {"source": "Mabeuf", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gavroche", "value": 1},
        {"source": "Enjolras", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Marius", "value": 7},
        {"source": "Enjolras", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gavroche", "value": 7},
        {"source": "Enjolras", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Javert", "value": 6},
        {"source": "Enjolras", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mabeuf", "value": 1},
        {"source": "Enjolras", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 4},
        {"source": "Combeferre", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Enjolras", "value": 15},
        {"source": "Combeferre", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Marius", "value": 5},
        {"source": "Combeferre", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gavroche", "value": 6},
        {"source": "Combeferre", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mabeuf", "value": 2},
        {"source": "Prouvaire", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gavroche", "value": 1},
        {"source": "Prouvaire", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Enjolras", "value": 4},
        {"source": "Prouvaire", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Combeferre", "value": 2},
        {"source": "Feuilly", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gavroche", "value": 2},
        {"source": "Feuilly", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Enjolras", "value": 6},
        {"source": "Feuilly", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Prouvaire", "value": 2},
        {"source": "Feuilly", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Combeferre", "value": 5},
        {"source": "Feuilly", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mabeuf", "value": 1},
        {"source": "Feuilly", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Marius", "value": 1},
        {"source": "Courfeyrac", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Marius", "value": 9},
        {"source": "Courfeyrac", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Enjolras", "value": 17},
        {"source": "Courfeyrac", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Combeferre", "value": 13},
        {"source": "Courfeyrac", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gavroche", "value": 7},
        {"source": "Courfeyrac", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mabeuf", "value": 2},
        {"source": "Courfeyrac", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Eponine", "value": 1},
        {"source": "Courfeyrac", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Feuilly", "value": 6},
        {"source": "Courfeyrac", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Prouvaire", "value": 3},
        {"source": "Bahorel", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Combeferre", "value": 5},
        {"source": "Bahorel", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gavroche", "value": 5},
        {"source": "Bahorel", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Courfeyrac", "value": 6},
        {"source": "Bahorel", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mabeuf", "value": 2},
        {"source": "Bahorel", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Enjolras", "value": 4},
        {"source": "Bahorel", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Feuilly", "value": 3},
        {"source": "Bahorel", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Prouvaire", "value": 2},
        {"source": "Bahorel", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Marius", "value": 1},
        {"source": "Bossuet", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Marius", "value": 5},
        {"source": "Bossuet", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Courfeyrac", "value": 12},
        {"source": "Bossuet", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gavroche", "value": 5},
        {"source": "Bossuet", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Bahorel", "value": 4},
        {"source": "Bossuet", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Enjolras", "value": 10},
        {"source": "Bossuet", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Feuilly", "value": 6},
        {"source": "Bossuet", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Prouvaire", "value": 2},
        {"source": "Bossuet", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Combeferre", "value": 9},
        {"source": "Bossuet", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mabeuf", "value": 1},
        {"source": "Bossuet", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 1},
        {"source": "Joly", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Bahorel", "value": 5},
        {"source": "Joly", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Bossuet", "value": 7},
        {"source": "Joly", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gavroche", "value": 3},
        {"source": "Joly", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Courfeyrac", "value": 5},
        {"source": "Joly", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Enjolras", "value": 5},
        {"source": "Joly", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Feuilly", "value": 5},
        {"source": "Joly", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Prouvaire", "value": 2},
        {"source": "Joly", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Combeferre", "value": 5},
        {"source": "Joly", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mabeuf", "value": 1},
        {"source": "Joly", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Marius", "value": 2},
        {"source": "Grantaire", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Bossuet", "value": 3},
        {"source": "Grantaire", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Enjolras", "value": 3},
        {"source": "Grantaire", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Combeferre", "value": 1},
        {"source": "Grantaire", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Courfeyrac", "value": 2},
        {"source": "Grantaire", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Joly", "value": 2},
        {"source": "Grantaire", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gavroche", "value": 1},
        {"source": "Grantaire", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Bahorel", "value": 1},
        {"source": "Grantaire", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Feuilly", "value": 1},
        {"source": "Grantaire", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Prouvaire", "value": 1},
        {"source": "MotherPlutarch", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mabeuf", "value": 3},
        {"source": "Gueulemer", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Thenardier", "value": 5},
        {"source": "Gueulemer", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 1},
        {"source": "Gueulemer", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mme.Thenardier", "value": 1},
        {"source": "Gueulemer", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Javert", "value": 1},
        {"source": "Gueulemer", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gavroche", "value": 1},
        {"source": "Gueulemer", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Eponine", "value": 1},
        {"source": "Babet", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Thenardier", "value": 6},
        {"source": "Babet", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gueulemer", "value": 6},
        {"source": "Babet", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 1},
        {"source": "Babet", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mme.Thenardier", "value": 1},
        {"source": "Babet", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Javert", "value": 2},
        {"source": "Babet", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gavroche", "value": 1},
        {"source": "Babet", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Eponine", "value": 1},
        {"source": "Claquesous", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Thenardier", "value": 4},
        {"source": "Claquesous", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Babet", "value": 4},
        {"source": "Claquesous", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gueulemer", "value": 4},
        {"source": "Claquesous", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 1},
        {"source": "Claquesous", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Mme.Thenardier", "value": 1},
        {"source": "Claquesous", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Javert", "value": 1},
        {"source": "Claquesous", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Eponine", "value": 1},
        {"source": "Claquesous", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Enjolras", "value": 1},
        {"source": "Montparnasse", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Javert", "value": 1},
        {"source": "Montparnasse", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Babet", "value": 2},
        {"source": "Montparnasse", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gueulemer", "value": 2},
        {"source": "Montparnasse", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Claquesous", "value": 2},
        {"source": "Montparnasse", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 1},
        {"source": "Montparnasse", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gavroche", "value": 1},
        {"source": "Montparnasse", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Eponine", "value": 1},
        {"source": "Montparnasse", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Thenardier", "value": 1},
        {"source": "Toussaint", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Cosette", "value": 2},
        {"source": "Toussaint", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Javert", "value": 1},
        {"source": "Toussaint", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Valjean", "value": 1},
        {"source": "Child1", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gavroche", "value": 2},
        {"source": "Child2", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gavroche", "value": 2},
        {"source": "Child2", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Child1", "value": 3},
        {"source": "Brujon", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Babet", "value": 3},
        {"source": "Brujon", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gueulemer", "value": 3},
        {"source": "Brujon", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Thenardier", "value": 3},
        {"source": "Brujon", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gavroche", "value": 1},
        {"source": "Brujon", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Eponine", "value": 1},
        {"source": "Brujon", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Claquesous", "value": 1},
        {"source": "Brujon", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Montparnasse", "value": 1},
        {"source": "Mme.Hucheloup", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Bossuet", "value": 1},
        {"source": "Mme.Hucheloup", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Joly", "value": 1},
        {"source": "Mme.Hucheloup", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Grantaire", "value": 1},
        {"source": "Mme.Hucheloup", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Bahorel", "value": 1},
        {"source": "Mme.Hucheloup", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Courfeyrac", "value": 1},
        {"source": "Mme.Hucheloup", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Gavroche", "value": 1},
        {"source": "Mme.Hucheloup", "curvature": "0.5","rotation": Math.PI * 1 / 6,"target": "Enjolras", "value": 1}
      ]
    }
    // const Graph = ForceGraph3D()
    //     (document.getElementById('3d-graph'))
    //     .linkCurvature('curvature')
    //     .linkCurveRotation('rotation')
    //     .linkDirectionalParticles(2)
    //     .graphData(gData);
    return (
        <div>
            <ForceGraph3D
                linkDirectionalParticles="2"
                nodeAutoColorBy="group"
                nodeLabel="id"
                linkDirectionalParticles="value"
                linkLabel = "value"
                graphData={gData} />
        </div>)
}

export default Canvas
